name: Get neofetch-style profile SVGs.

on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0 * * *" }]
  # Manual trigger
  workflow_dispatch:
  # Push to main branches
  push: { branches: ["master", "main"] }

jobs:
  profilefetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run profilefetch script
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python profilefetch.py

      - name: Update SVGs in repository
        # If the last commit was made by github-actions[bot], amend and force push.
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          python action-amend-commit.py
